# Use the latest verson of alpine
FROM node:current-alpine

# Setting up working directory inside the container
WORKDIR /app

COPY node-backend/package*.json ./

# Install Dependencies
RUN npm install

# Copy the rest of app files
COPY . .

EXPOSE 3000