# Use the latest verson of alpine
FROM node:current-alpine

# Setting up working directory inside the container
WORKDIR /app

COPY node-backend/package*.json ./

# Install Dependencies
RUN npm install

# Copy the rest of app files
COPY node-backend/ .

EXPOSE 3000

CMD ["node", "server.js"]